name: pycon-sponsors
channels:
    - scrapinghub
dependencies:
    - python=3.5
    - scrapy=1.1.*
    - sqlalchemy=1.1.*
    - pymysql=0.7.*
    - pylint=1.5.*
    - pycodestyle=2.2.*
    - pydocstyle=1.1.*
